package no.nav.syfo.vault

class VaultError(message: String, cause: Throwable) : Exception(message, cause)